import "./globals.css";
import InstructorFooter from "../(instructor)/instructor/instractorFooter/page";
import Header from "@/app/_components/Header/Header";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Toaster } from "sonner";

export const metadata = {
  title: "Online Courses - Learn Anything, On Your Schedule | Udemy",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  if (!routing.locales.includes(locale)) {
    NotFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale} dir={`${locale === "ar" ? "rtl" : "ltr"}`}>
      <body className="font-sans">
        <NextIntlClientProvider messages={messages}>
          <Header locale={locale} />
          {children}

          <Toaster position="bottom-right" />
          <div>
            <InstructorFooter />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
