import AuthProvider from "../context/AuthProvider";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { redirect } from "next/dist/server/api-utils";
import { Toaster } from "sonner";

export const metadata = {
  title: "Online Courses - Learn Anything, On Your Schedule | Udemy",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  if (!routing.locales.includes(locale)) {
   redirect(`/${locale}/`)
  }
  const messages = await getMessages();
  return (
    <html lang={locale} dir={`${locale === "ar" ? "rtl" : "ltr"}`}>
      <body className="font-sans">
        <NextIntlClientProvider messages={messages}>
          <AuthProvider>
            {children}
            <Toaster position="bottom-right" />
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
