import AuthProvider from "@/app/context/AuthProvider";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import { Toaster } from "sonner";
import { notFound } from "next/navigation";
import "./globals.css";
import { getSession } from "@/lib/auth";

export const metadata = {
  title: "Online Courses - Learn Anything, On Your Schedule | Udemy",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
  if (!routing.locales.includes(locale)) {
    notFound();
  }
  const messages = await getMessages();
  const session = await getSession();

  return (
    <html lang={locale} dir={`${locale === "ar" ? "rtl" : "ltr"}`}>
      <body className="font-sans">
        <NextIntlClientProvider messages={messages}>
          <AuthProvider session={session}>
            {children}

            <Toaster position="bottom-right" />
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
