import localFont from "next/font/local";
import Header from "../_components/Header/Header";
import Footer from "../_components/Footer/Footer";
import "./globals.css";
import InstructorFooter from "../(instructor)/instructor/instractorFooter/page";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans">
        <Header />
        {children}
        <Toaster position="bottom-right" />
        <div>
          <InstructorFooter />
        </div>
      </body>
    </html>
  );
}
